### ISSUE TITLE
Playing with the schema

### ISSUE THREAD

**Issue by szepeviktor** [hypnotox/abyss#7]
```yaml
- name: "person's name"
  key: "name"
  value-type: "string"
  constraints:
    - min_length: 2
    - max_length: 40
- key: "age"
  value-type: "integer"
  constraints:
    - min_value: 18
    - max_value: 120
- key: "ratings"
  value-type: "array"
  elements:
    - key: "silly"
      value-type: "float"
      constraints:
        - min_value: -1.0
    - key: "billy"
      value-type: "float"
- key: "attributes"
  value-type: "list"
  elements:
    - value-type: "string"
      constraints:
        - min_length: 1
- key: "mess"
  value-type: "array"
  elements:
    - key-type: "integer"
      value-type: "string"
```

**Comment by szepeviktor** [comment]
We could be much-much popular if we process PHP DocBlock-like types.

```yaml
- name: "person's attrs"
  element: "list<string> $attributes"
  constraints:
    - value-regexp: "^[a-z_]+$"
- element: "int<18, 120> $age"
- name: "big MESS"
  element: "array<int, mixed> $mess"
```

**Comment by szepeviktor** [comment]
Actually the best libraries are built around **real life** problems.

**Comment by szepeviktor** [comment]
While going further I've stumbled upon schema-less object mapping.

```php
$arrayOfBookData = $api->getResponseArray();
// small validation :)
Abyss::validate($arrayOfBookData, 'list<array>'); // throws exception when invalid

foreach ($arrayOfBookData as $bookData) {
    $bookInstance = Abyss::mapToObject($bookData, Book::class); // throws exception when invalid
    // do something with $bookInstance
}
```

That's it. All Book details should be in `Book` class as typehints, PHP DocBlocks, PHP 8 Attributes ...

**Comment by szepeviktor** [comment]
End we could end up with https://valinor.cuyz.io/latest/getting-started/

**Comment by szepeviktor** [comment]
@hypnotox I know - I know, you want to help developers in the _array business_.

**Comment by hypnotox** [comment]
> Actually the best libraries are built around real life problems.

I agree 👍🏻 

I'm still thinking about possible ways to define constraints, I'll probably change it a bit from how i have the classes in right now.

My current idea for array value types would be this:

```yaml
# Type definitions for array types

# list<int>
- type: array
  constraints:
    key:
      - index # expects a sequential int starting from 0
    value:
      - int # any int

# list<int<1,10>>
- type: array
  constraints:
    key:
      - index
    value:
      - int<1,10> # any int from 1 to 10

- type: array
  constraints:
    key:
      - index
    value:
      int:
        min: 1
        max: 10

# map<int, string>
- type: array
  constraints:
    key:
      - int
    value:
      - string

# map<string, string>
- type: array
  constraints:
    key:
      - string
    value:
      - string
```

Something that I'm still very unsure about is how the root node should be defined, or repeating nodes / patterns for that matter:

```yaml
# Idea for repeating patterns

# map<string, int>(5)
- type: array
  repeats: 5 # 5 elements following each other
  constraints:
    key:
      - string
    value:
      - int # any int
```

> I know - I know, you want to help developers in the array business.

The library should stay focused for now, fetching the schema from a class / object sounds nice for sure, but I'd put that on the "possible future features" list. If i would implement this in the future I'd probably build a secondary library that builds an object mapper using the object schema validation too :)
